
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://*****/mybatis_plus_db?useUnicode=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ***
    password: ***
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/blues/lin/mpauto/**/*Mapper.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

# mybatis actable配置
actable:
  table:
    auto: none # create 每次都删 update 只更新不删数据 none 不做处理 add 只新增不修改
  model:
    pack: com.blues.lin.mpauto.entity
  database:
    type: mysql
